version: 2
jobs:
  build:
    working_directory: ~/whadido
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Install deps
          command: yarn install --ignore-engines

      - save_cache:
          key: dependency-cache-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Checkout submodule
          command: git submodule init && git submodule update --remote

      # - run:
      #     name: Build (webpack dev)
      #     command: npm run webpack

      # - run:
      #     name: Build (webpack prod)
      #     command: npm run webpack:prod

      # - run:
      #     name: Build (tsc)
      #     command: npm run build

      # - run:
      #     name: Run tslint
      #     command: npm run tslint

      - run:
          name: Test
          command: yarn test

      - run:
          name: Measure Test Coverage
          command: yarn test:coverage

      - run:
          name: Upload Coverage
          command: yarn codecov

      # - store_artifacts:
      #     path: coverage
      #     prefix: coverage
